# Generated by Django 5.2.7 on 2025-10-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organization_created_by_and_more'),
        ('projects', '0005_project_end_date_project_start_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('organization', 'name')},
        ),
    ]
