# Generated by Django 5.2.7 on 2025-10-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='visibility',
        ),
    ]
