# Generated by Django 5.2.7 on 2025-10-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
