# Generated by Django 5.2.7 on 2025-10-17 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_visibility'),
        ('tasks', '0003_taskstatus_is_default_taskstatus_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.CreateModel(
            name='TaskMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_tasks', to='projects.projectmember')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_members', to='tasks.task')),
            ],
            options={
                'unique_together': {('task', 'member')},
            },
        ),
    ]
