# Generated by Django 5.2.7 on 2025-11-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_taskdeadlineextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='task_comments/'),
        ),
    ]
