# Generated by Django 5.2.7 on 2025-11-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_taskcomment_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
