# Generated by Django 5.2.7 on 2025-11-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0011_taskstatushistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskcomment",
            name="mentions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
