# Generated by Django 5.2.7 on 2025-10-17 12:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organization_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationMembership',
            new_name='OrganizationMember',
        ),
        migrations.RenameIndex(
            model_name='organizationmember',
            new_name='organizatio_organiz_8fe467_idx',
            old_name='organizatio_organiz_e1169f_idx',
        ),
    ]
