# Generated by Django 5.2.7 on 2025-10-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_rename_organizationmembership_organizationmember_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationinvitation',
            name='invited_by',
        ),
    ]
